# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'TestA.xcworkspace' # workspace文件名（下面的路径都是相对于xcworkspace的路径，它是项目的根路径）

# 主项目
target 'TestA' do
  project 'TestA.xcodeproj' # 指定主工程路径（导入指令：用xcodeproj或project都可以）
  pod 'AFNetworking', '~> 3.1.0'

end

# 子项目1（APP项目）
target 'TestB' do
    project '../TestB/TestB.xcodeproj' # 指定子工程路径
    pod 'YYKit', '~> 1.0.9'

end

# 子项目2（静态库项目）
target 'TestC' do
    project '../TestC/TestC.xcodeproj' # 指定子工程路径
    
end

